services:
  inventory-locatory-api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    working_dir: /app
    ports:
      - "3333:3000"
    env_file:
      - ../.env
    volumes:
      - ../:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge
