name: id_scanner
description: "ID Scanner Mobile App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-174.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  provider: ^6.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.2.3
  encrypt: ^5.0.3
  intl: ^0.19.0
  location: ^7.0.0
  device_info_plus: ^10.1.2
  http: ^1.2.2
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  image: ^4.3.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true